version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 16
    on-failure: ABORT
    commands:
      - | 
        npm install
  pre_build:
    on-failure: ABORT
    commands:
      - |
        npm run test