version: 0.2

cache:
  paths:
    - node_modules/**/*

env:
  shell: bash

phases:
    install:
      runtime-versions:
        nodejs: 16
      on-failure: ABORT
      commands:
        - npm install
    build:
      on-failure: ABORT
      commands:
        - |
          if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
            npm run build:about
          fi
    post_build:
      on-failure: ABORT
      commands:
        - |
          if [[ ($GITHUB_EVENT_NAME == "push") ]]; then 
            aws s3 cp dist s3://${DEPLOY_S3}/about  --recursive 
          fi
