import { createDomText } from "./utils/dom"
const title = createDomText("h1", "this is about page")
const description = createDomText("p", "this is about page description")
const description2 = createDomText("p", "this is about page description2")
const description3 = createDomText("p", "this is about page description3")
const app = document.querySelector("#app")
app.appendChild(title)
app.appendChild(description)
app.appendChild(description2)
app.appendChild(description3)
